//! Code generated by sqlc-gen-rust. SHOULD NOT EDIT.
//! sqlc version: v1.31.1
//! sqlc-gen-rust version: v0.1.11
use deadpool_sqlite::rusqlite;

pub trait RusqliteClient {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>>;
}
impl RusqliteClient for rusqlite::Connection {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>> {
        self.prepare(sql)
    }
}
impl RusqliteClient for rusqlite::Transaction<'_> {
    fn prepare(&self, sql: &str) -> rusqlite::Result<rusqlite::Statement<'_>> {
        rusqlite::Connection::prepare(&self, sql)
    }
}
pub struct GetAdminsRow {
    pub admins: String,
}
impl GetAdminsRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            admins: row.get(0)?,
        })
    }
}
pub struct GetAdmins;
impl GetAdmins {
    pub const QUERY: &'static str = r"
SELECT admins FROM config";
    pub fn query_one(&self, client: &impl RusqliteClient) -> rusqlite::Result<GetAdminsRow> {
        Self::prepare(client)?.query_row(self.as_params(), GetAdminsRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<GetAdminsRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), GetAdminsRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl GetAdmins {
    pub const fn builder() -> GetAdminsBuilder<'static, ()> {
        GetAdminsBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetAdminsBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> GetAdminsBuilder<'a, ()> {
    pub const fn build(self) -> GetAdmins {
        let () = self.fields;
        GetAdmins {}
    }
}
pub struct AddAdminRow {}
impl AddAdminRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {})
    }
}
pub struct AddAdmin {
    json_set: f64,
}
impl AddAdmin {
    pub const QUERY: &'static str = r"UPDATE  config
SET     admins = json_set(admins, '$[#]', ?1)";
    pub fn execute(&self, client: &impl RusqliteClient) -> rusqlite::Result<usize> {
        Self::prepare(client)?.execute(self.as_params())
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (f64,) {
        (self.json_set,)
    }
}
impl AddAdmin {
    pub const fn builder() -> AddAdminBuilder<'static, ((),)> {
        AddAdminBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct AddAdminBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> AddAdminBuilder<'a, ((),)> {
    pub fn json_set(self, json_set: f64) -> AddAdminBuilder<'a, (f64,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        AddAdminBuilder {
            fields: (json_set,),
            _phantom,
        }
    }
}
impl<'a> AddAdminBuilder<'a, (f64,)> {
    pub const fn build(self) -> AddAdmin {
        let (json_set,) = self.fields;
        AddAdmin { json_set }
    }
}
pub struct SetAdminsRow {}
impl SetAdminsRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {})
    }
}
pub struct SetAdmins<'a> {
    admins: &'a str,
}
impl<'a> SetAdmins<'a> {
    pub const QUERY: &'static str = r"UPDATE config SET admins = ?1";
    pub fn execute(&self, client: &impl RusqliteClient) -> rusqlite::Result<usize> {
        Self::prepare(client)?.execute(self.as_params())
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (&'a str,) {
        (self.admins,)
    }
}
impl<'a> SetAdmins<'a> {
    pub const fn builder() -> SetAdminsBuilder<'a, ((),)> {
        SetAdminsBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct SetAdminsBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> SetAdminsBuilder<'a, ((),)> {
    pub fn admins(self, admins: &'a str) -> SetAdminsBuilder<'a, (&'a str,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        SetAdminsBuilder {
            fields: (admins,),
            _phantom,
        }
    }
}
impl<'a> SetAdminsBuilder<'a, (&'a str,)> {
    pub const fn build(self) -> SetAdmins<'a> {
        let (admins,) = self.fields;
        SetAdmins { admins }
    }
}
pub struct GetTreasuryNotificationsChatIdRow {
    pub treasury_notifications_chat_id: Option<i64>,
}
impl GetTreasuryNotificationsChatIdRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            treasury_notifications_chat_id: row.get(0)?,
        })
    }
}
pub struct GetTreasuryNotificationsChatId;
impl GetTreasuryNotificationsChatId {
    pub const QUERY: &'static str = r"SELECT treasury_notifications_chat_id FROM config";
    pub fn query_one(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<GetTreasuryNotificationsChatIdRow> {
        Self::prepare(client)?.query_row(
            self.as_params(),
            GetTreasuryNotificationsChatIdRow::from_row,
        )
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<GetTreasuryNotificationsChatIdRow>> {
        Self::prepare(client)?
            .query_map(
                self.as_params(),
                GetTreasuryNotificationsChatIdRow::from_row,
            )?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl GetTreasuryNotificationsChatId {
    pub const fn builder() -> GetTreasuryNotificationsChatIdBuilder<'static, ()> {
        GetTreasuryNotificationsChatIdBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetTreasuryNotificationsChatIdBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> GetTreasuryNotificationsChatIdBuilder<'a, ()> {
    pub const fn build(self) -> GetTreasuryNotificationsChatId {
        let () = self.fields;
        GetTreasuryNotificationsChatId {}
    }
}
pub struct SetTreasuryNotificationsChatIdRow {}
impl SetTreasuryNotificationsChatIdRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {})
    }
}
pub struct SetTreasuryNotificationsChatId {
    treasury_notifications_chat_id: Option<i64>,
}
impl SetTreasuryNotificationsChatId {
    pub const QUERY: &'static str = r"UPDATE config SET treasury_notifications_chat_id = ?1";
    pub fn execute(&self, client: &impl RusqliteClient) -> rusqlite::Result<usize> {
        Self::prepare(client)?.execute(self.as_params())
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (Option<i64>,) {
        (self.treasury_notifications_chat_id,)
    }
}
impl SetTreasuryNotificationsChatId {
    pub const fn builder() -> SetTreasuryNotificationsChatIdBuilder<'static, ((),)> {
        SetTreasuryNotificationsChatIdBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct SetTreasuryNotificationsChatIdBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> SetTreasuryNotificationsChatIdBuilder<'a, ((),)> {
    pub fn treasury_notifications_chat_id(
        self,
        treasury_notifications_chat_id: Option<i64>,
    ) -> SetTreasuryNotificationsChatIdBuilder<'a, (Option<i64>,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        SetTreasuryNotificationsChatIdBuilder {
            fields: (treasury_notifications_chat_id,),
            _phantom,
        }
    }
}
impl<'a> SetTreasuryNotificationsChatIdBuilder<'a, (Option<i64>,)> {
    pub const fn build(self) -> SetTreasuryNotificationsChatId {
        let (treasury_notifications_chat_id,) = self.fields;
        SetTreasuryNotificationsChatId {
            treasury_notifications_chat_id,
        }
    }
}
pub struct GetAssemblyMinutesChatIdRow {
    pub assembly_minutes_chat_id: Option<i64>,
}
impl GetAssemblyMinutesChatIdRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            assembly_minutes_chat_id: row.get(0)?,
        })
    }
}
pub struct GetAssemblyMinutesChatId;
impl GetAssemblyMinutesChatId {
    pub const QUERY: &'static str = r"SELECT assembly_minutes_chat_id FROM config";
    pub fn query_one(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<GetAssemblyMinutesChatIdRow> {
        Self::prepare(client)?.query_row(self.as_params(), GetAssemblyMinutesChatIdRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<GetAssemblyMinutesChatIdRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), GetAssemblyMinutesChatIdRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl GetAssemblyMinutesChatId {
    pub const fn builder() -> GetAssemblyMinutesChatIdBuilder<'static, ()> {
        GetAssemblyMinutesChatIdBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetAssemblyMinutesChatIdBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> GetAssemblyMinutesChatIdBuilder<'a, ()> {
    pub const fn build(self) -> GetAssemblyMinutesChatId {
        let () = self.fields;
        GetAssemblyMinutesChatId {}
    }
}
pub struct SetAssemblyMinutesChatIdRow {}
impl SetAssemblyMinutesChatIdRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {})
    }
}
pub struct SetAssemblyMinutesChatId {
    assembly_minutes_chat_id: Option<i64>,
}
impl SetAssemblyMinutesChatId {
    pub const QUERY: &'static str = r"UPDATE config SET assembly_minutes_chat_id = ?1";
    pub fn execute(&self, client: &impl RusqliteClient) -> rusqlite::Result<usize> {
        Self::prepare(client)?.execute(self.as_params())
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (Option<i64>,) {
        (self.assembly_minutes_chat_id,)
    }
}
impl SetAssemblyMinutesChatId {
    pub const fn builder() -> SetAssemblyMinutesChatIdBuilder<'static, ((),)> {
        SetAssemblyMinutesChatIdBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct SetAssemblyMinutesChatIdBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> SetAssemblyMinutesChatIdBuilder<'a, ((),)> {
    pub fn assembly_minutes_chat_id(
        self,
        assembly_minutes_chat_id: Option<i64>,
    ) -> SetAssemblyMinutesChatIdBuilder<'a, (Option<i64>,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        SetAssemblyMinutesChatIdBuilder {
            fields: (assembly_minutes_chat_id,),
            _phantom,
        }
    }
}
impl<'a> SetAssemblyMinutesChatIdBuilder<'a, (Option<i64>,)> {
    pub const fn build(self) -> SetAssemblyMinutesChatId {
        let (assembly_minutes_chat_id,) = self.fields;
        SetAssemblyMinutesChatId {
            assembly_minutes_chat_id,
        }
    }
}
pub struct GetFestAttendeesRow {
    pub legalname: String,
    pub codename: String,
    pub haspaid: i64,
    pub assiststo: String,
    pub allergies: Option<String>,
    pub diet: i64,
}
impl GetFestAttendeesRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            legalname: row.get(0)?,
            codename: row.get(1)?,
            haspaid: row.get(2)?,
            assiststo: row.get(3)?,
            allergies: row.get(4)?,
            diet: row.get(5)?,
        })
    }
}
pub struct GetFestAttendees;
impl GetFestAttendees {
    pub const QUERY: &'static str =
        r"SELECT legalname, codename, haspaid, assiststo, allergies, diet FROM festAttendee";
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<GetFestAttendeesRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), GetFestAttendeesRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl GetFestAttendees {
    pub const fn builder() -> GetFestAttendeesBuilder<'static, ()> {
        GetFestAttendeesBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetFestAttendeesBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> GetFestAttendeesBuilder<'a, ()> {
    pub const fn build(self) -> GetFestAttendees {
        let () = self.fields;
        GetFestAttendees {}
    }
}
pub struct HasPaidFestRow {
    pub haspaid: i64,
}
impl HasPaidFestRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            haspaid: row.get(0)?,
        })
    }
}
pub struct HasPaidFest<'a> {
    codename: &'a str,
}
impl<'a> HasPaidFest<'a> {
    pub const QUERY: &'static str = r"SELECT hasPaid FROM festAttendee WHERE codeName = ?1";
    pub fn query_one(&self, client: &impl RusqliteClient) -> rusqlite::Result<HasPaidFestRow> {
        Self::prepare(client)?.query_row(self.as_params(), HasPaidFestRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<HasPaidFestRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), HasPaidFestRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (&'a str,) {
        (self.codename,)
    }
}
impl<'a> HasPaidFest<'a> {
    pub const fn builder() -> HasPaidFestBuilder<'a, ((),)> {
        HasPaidFestBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct HasPaidFestBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> HasPaidFestBuilder<'a, ((),)> {
    pub fn codename(self, codename: &'a str) -> HasPaidFestBuilder<'a, (&'a str,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        HasPaidFestBuilder {
            fields: (codename,),
            _phantom,
        }
    }
}
impl<'a> HasPaidFestBuilder<'a, (&'a str,)> {
    pub const fn build(self) -> HasPaidFest<'a> {
        let (codename,) = self.fields;
        HasPaidFest { codename }
    }
}
pub struct LegalNameSetPaidRow {}
impl LegalNameSetPaidRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {})
    }
}
pub struct LegalNameSetPaid<'a> {
    legalname: &'a str,
    haspaid: i64,
}
impl<'a> LegalNameSetPaid<'a> {
    pub const QUERY: &'static str = r"UPDATE festAttendee SET hasPaid = ?2 WHERE legalName = ?1";
    pub fn execute(&self, client: &impl RusqliteClient) -> rusqlite::Result<usize> {
        Self::prepare(client)?.execute(self.as_params())
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (&'a str, i64) {
        (self.legalname, self.haspaid)
    }
}
impl<'a> LegalNameSetPaid<'a> {
    pub const fn builder() -> LegalNameSetPaidBuilder<'a, ((), ())> {
        LegalNameSetPaidBuilder {
            fields: ((), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct LegalNameSetPaidBuilder<'a, Fields = ((), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Haspaid> LegalNameSetPaidBuilder<'a, ((), Haspaid)> {
    pub fn legalname(self, legalname: &'a str) -> LegalNameSetPaidBuilder<'a, (&'a str, Haspaid)> {
        let ((), haspaid) = self.fields;
        let _phantom = self._phantom;
        LegalNameSetPaidBuilder {
            fields: (legalname, haspaid),
            _phantom,
        }
    }
}
impl<'a, Legalname> LegalNameSetPaidBuilder<'a, (Legalname, ())> {
    pub fn haspaid(self, haspaid: i64) -> LegalNameSetPaidBuilder<'a, (Legalname, i64)> {
        let (legalname, ()) = self.fields;
        let _phantom = self._phantom;
        LegalNameSetPaidBuilder {
            fields: (legalname, haspaid),
            _phantom,
        }
    }
}
impl<'a> LegalNameSetPaidBuilder<'a, (&'a str, i64)> {
    pub const fn build(self) -> LegalNameSetPaid<'a> {
        let (legalname, haspaid) = self.fields;
        LegalNameSetPaid { legalname, haspaid }
    }
}
pub struct NewFestAttendeeRow {}
impl NewFestAttendeeRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {})
    }
}
pub struct NewFestAttendee<'a> {
    legalname: &'a str,
    codename: &'a str,
    assiststo: &'a str,
    allergies: Option<&'a str>,
    diet: i64,
}
impl<'a> NewFestAttendee<'a> {
    pub const QUERY: &'static str = r"INSERT INTO festAttendee (legalName, codeName, assistsTo, allergies, diet) VALUES (?1, ?2, ?3, ?4, ?5)";
    pub fn execute(&self, client: &impl RusqliteClient) -> rusqlite::Result<usize> {
        Self::prepare(client)?.execute(self.as_params())
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (&'a str, &'a str, &'a str, Option<&'a str>, i64) {
        (
            self.legalname,
            self.codename,
            self.assiststo,
            self.allergies,
            self.diet,
        )
    }
}
impl<'a> NewFestAttendee<'a> {
    pub const fn builder() -> NewFestAttendeeBuilder<'a, ((), (), (), (), ())> {
        NewFestAttendeeBuilder {
            fields: ((), (), (), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct NewFestAttendeeBuilder<'a, Fields = ((), (), (), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Codename, Assiststo, Allergies, Diet>
    NewFestAttendeeBuilder<'a, ((), Codename, Assiststo, Allergies, Diet)>
{
    pub fn legalname(
        self,
        legalname: &'a str,
    ) -> NewFestAttendeeBuilder<'a, (&'a str, Codename, Assiststo, Allergies, Diet)> {
        let ((), codename, assiststo, allergies, diet) = self.fields;
        let _phantom = self._phantom;
        NewFestAttendeeBuilder {
            fields: (legalname, codename, assiststo, allergies, diet),
            _phantom,
        }
    }
}
impl<'a, Legalname, Assiststo, Allergies, Diet>
    NewFestAttendeeBuilder<'a, (Legalname, (), Assiststo, Allergies, Diet)>
{
    pub fn codename(
        self,
        codename: &'a str,
    ) -> NewFestAttendeeBuilder<'a, (Legalname, &'a str, Assiststo, Allergies, Diet)> {
        let (legalname, (), assiststo, allergies, diet) = self.fields;
        let _phantom = self._phantom;
        NewFestAttendeeBuilder {
            fields: (legalname, codename, assiststo, allergies, diet),
            _phantom,
        }
    }
}
impl<'a, Legalname, Codename, Allergies, Diet>
    NewFestAttendeeBuilder<'a, (Legalname, Codename, (), Allergies, Diet)>
{
    pub fn assiststo(
        self,
        assiststo: &'a str,
    ) -> NewFestAttendeeBuilder<'a, (Legalname, Codename, &'a str, Allergies, Diet)> {
        let (legalname, codename, (), allergies, diet) = self.fields;
        let _phantom = self._phantom;
        NewFestAttendeeBuilder {
            fields: (legalname, codename, assiststo, allergies, diet),
            _phantom,
        }
    }
}
impl<'a, Legalname, Codename, Assiststo, Diet>
    NewFestAttendeeBuilder<'a, (Legalname, Codename, Assiststo, (), Diet)>
{
    pub fn allergies(
        self,
        allergies: Option<&'a str>,
    ) -> NewFestAttendeeBuilder<'a, (Legalname, Codename, Assiststo, Option<&'a str>, Diet)> {
        let (legalname, codename, assiststo, (), diet) = self.fields;
        let _phantom = self._phantom;
        NewFestAttendeeBuilder {
            fields: (legalname, codename, assiststo, allergies, diet),
            _phantom,
        }
    }
}
impl<'a, Legalname, Codename, Assiststo, Allergies>
    NewFestAttendeeBuilder<'a, (Legalname, Codename, Assiststo, Allergies, ())>
{
    pub fn diet(
        self,
        diet: i64,
    ) -> NewFestAttendeeBuilder<'a, (Legalname, Codename, Assiststo, Allergies, i64)> {
        let (legalname, codename, assiststo, allergies, ()) = self.fields;
        let _phantom = self._phantom;
        NewFestAttendeeBuilder {
            fields: (legalname, codename, assiststo, allergies, diet),
            _phantom,
        }
    }
}
impl<'a> NewFestAttendeeBuilder<'a, (&'a str, &'a str, &'a str, Option<&'a str>, i64)> {
    pub const fn build(self) -> NewFestAttendee<'a> {
        let (legalname, codename, assiststo, allergies, diet) = self.fields;
        NewFestAttendee {
            legalname,
            codename,
            assiststo,
            allergies,
            diet,
        }
    }
}
pub struct GetAttendessNamesRow {
    pub codename: String,
    pub legalname: String,
}
impl GetAttendessNamesRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            codename: row.get(0)?,
            legalname: row.get(1)?,
        })
    }
}
pub struct GetAttendessNames;
impl GetAttendessNames {
    pub const QUERY: &'static str = r"SELECT codeName, legalName from festAttendee";
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<GetAttendessNamesRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), GetAttendessNamesRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl GetAttendessNames {
    pub const fn builder() -> GetAttendessNamesBuilder<'static, ()> {
        GetAttendessNamesBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetAttendessNamesBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> GetAttendessNamesBuilder<'a, ()> {
    pub const fn build(self) -> GetAttendessNames {
        let () = self.fields;
        GetAttendessNames {}
    }
}
pub struct WhoGoesToSundalRow {
    pub codename: String,
}
impl WhoGoesToSundalRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            codename: row.get(0)?,
        })
    }
}
pub struct WhoGoesToSundal;
impl WhoGoesToSundal {
    pub const QUERY: &'static str = r"SELECT codeName FROM festAttendee a WHERE EXISTS (
    SELECT 1
    FROM json_each(a.assistsTo) AS place
    WHERE place.value = 'sundal'
) ORDER BY codeName";
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<WhoGoesToSundalRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), WhoGoesToSundalRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl WhoGoesToSundal {
    pub const fn builder() -> WhoGoesToSundalBuilder<'static, ()> {
        WhoGoesToSundalBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct WhoGoesToSundalBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> WhoGoesToSundalBuilder<'a, ()> {
    pub const fn build(self) -> WhoGoesToSundal {
        let () = self.fields;
        WhoGoesToSundal {}
    }
}
pub struct HowManyGoToSundalRow {
    pub count: i64,
}
impl HowManyGoToSundalRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self { count: row.get(0)? })
    }
}
pub struct HowManyGoToSundal;
impl HowManyGoToSundal {
    pub const QUERY: &'static str = r"SELECT COUNT(*) FROM festAttendee a WHERE EXISTS (
    SELECT 1
    FROM json_each(a.assistsTo) AS place
    WHERE place.value = 'sundal'
)";
    pub fn query_one(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<HowManyGoToSundalRow> {
        Self::prepare(client)?.query_row(self.as_params(), HowManyGoToSundalRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<HowManyGoToSundalRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), HowManyGoToSundalRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl HowManyGoToSundal {
    pub const fn builder() -> HowManyGoToSundalBuilder<'static, ()> {
        HowManyGoToSundalBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct HowManyGoToSundalBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> HowManyGoToSundalBuilder<'a, ()> {
    pub const fn build(self) -> HowManyGoToSundal {
        let () = self.fields;
        HowManyGoToSundal {}
    }
}
pub struct HowManyGoToBubuRow {
    pub count: i64,
}
impl HowManyGoToBubuRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self { count: row.get(0)? })
    }
}
pub struct HowManyGoToBubu;
impl HowManyGoToBubu {
    pub const QUERY: &'static str = r"SELECT COUNT(*) FROM festAttendee a WHERE EXISTS (
    SELECT 1
    FROM json_each(a.assistsTo) AS place
    WHERE place.value = 'bubu'
)";
    pub fn query_one(&self, client: &impl RusqliteClient) -> rusqlite::Result<HowManyGoToBubuRow> {
        Self::prepare(client)?.query_row(self.as_params(), HowManyGoToBubuRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<HowManyGoToBubuRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), HowManyGoToBubuRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl HowManyGoToBubu {
    pub const fn builder() -> HowManyGoToBubuBuilder<'static, ()> {
        HowManyGoToBubuBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct HowManyGoToBubuBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> HowManyGoToBubuBuilder<'a, ()> {
    pub const fn build(self) -> HowManyGoToBubu {
        let () = self.fields;
        HowManyGoToBubu {}
    }
}
pub struct HowManyGoToAlmuerzoRow {
    pub count: i64,
}
impl HowManyGoToAlmuerzoRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self { count: row.get(0)? })
    }
}
pub struct HowManyGoToAlmuerzo;
impl HowManyGoToAlmuerzo {
    pub const QUERY: &'static str = r"SELECT COUNT(*) FROM festAttendee a WHERE EXISTS (
    SELECT 1
    FROM json_each(a.assistsTo) AS place
    WHERE place.value = 'sundal'
)";
    pub fn query_one(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<HowManyGoToAlmuerzoRow> {
        Self::prepare(client)?.query_row(self.as_params(), HowManyGoToAlmuerzoRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<HowManyGoToAlmuerzoRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), HowManyGoToAlmuerzoRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl HowManyGoToAlmuerzo {
    pub const fn builder() -> HowManyGoToAlmuerzoBuilder<'static, ()> {
        HowManyGoToAlmuerzoBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct HowManyGoToAlmuerzoBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> HowManyGoToAlmuerzoBuilder<'a, ()> {
    pub const fn build(self) -> HowManyGoToAlmuerzo {
        let () = self.fields;
        HowManyGoToAlmuerzo {}
    }
}
pub struct HowManyStandardDietRow {
    pub count: i64,
}
impl HowManyStandardDietRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self { count: row.get(0)? })
    }
}
pub struct HowManyStandardDiet;
impl HowManyStandardDiet {
    pub const QUERY: &'static str =
        r"SELECT COUNT(*) FROM festAttendee WHERE diet = 0 AND allergies IS NULL";
    pub fn query_one(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<HowManyStandardDietRow> {
        Self::prepare(client)?.query_row(self.as_params(), HowManyStandardDietRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<HowManyStandardDietRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), HowManyStandardDietRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl HowManyStandardDiet {
    pub const fn builder() -> HowManyStandardDietBuilder<'static, ()> {
        HowManyStandardDietBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct HowManyStandardDietBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> HowManyStandardDietBuilder<'a, ()> {
    pub const fn build(self) -> HowManyStandardDiet {
        let () = self.fields;
        HowManyStandardDiet {}
    }
}
pub struct WhoVegetarianRow {
    pub codename: String,
}
impl WhoVegetarianRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            codename: row.get(0)?,
        })
    }
}
pub struct WhoVegetarian;
impl WhoVegetarian {
    pub const QUERY: &'static str = r"SELECT codeName FROM festAttendee WHERE diet = 1";
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<WhoVegetarianRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), WhoVegetarianRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl WhoVegetarian {
    pub const fn builder() -> WhoVegetarianBuilder<'static, ()> {
        WhoVegetarianBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct WhoVegetarianBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> WhoVegetarianBuilder<'a, ()> {
    pub const fn build(self) -> WhoVegetarian {
        let () = self.fields;
        WhoVegetarian {}
    }
}
pub struct WhoVeganRow {
    pub codename: String,
}
impl WhoVeganRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            codename: row.get(0)?,
        })
    }
}
pub struct WhoVegan;
impl WhoVegan {
    pub const QUERY: &'static str = r"SELECT codeName FROM festAttendee WHERE diet = 2";
    pub fn query_many(&self, client: &impl RusqliteClient) -> rusqlite::Result<Vec<WhoVeganRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), WhoVeganRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl WhoVegan {
    pub const fn builder() -> WhoVeganBuilder<'static, ()> {
        WhoVeganBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct WhoVeganBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> WhoVeganBuilder<'a, ()> {
    pub const fn build(self) -> WhoVegan {
        let () = self.fields;
        WhoVegan {}
    }
}
pub struct WhoAllergiesRow {
    pub codename: String,
    pub allergies: Option<String>,
}
impl WhoAllergiesRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            codename: row.get(0)?,
            allergies: row.get(1)?,
        })
    }
}
pub struct WhoAllergies;
impl WhoAllergies {
    pub const QUERY: &'static str =
        r"SELECT codeName, allergies FROM festAttendee WHERE allergies IS NOT NULL";
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<WhoAllergiesRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), WhoAllergiesRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl WhoAllergies {
    pub const fn builder() -> WhoAllergiesBuilder<'static, ()> {
        WhoAllergiesBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct WhoAllergiesBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> WhoAllergiesBuilder<'a, ()> {
    pub const fn build(self) -> WhoAllergies {
        let () = self.fields;
        WhoAllergies {}
    }
}
pub struct RotatePointerRow {
    pub lastslot: i64,
}
impl RotatePointerRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            lastslot: row.get(0)?,
        })
    }
}
pub struct RotatePointer {
    userid: i64,
}
impl RotatePointer {
    pub const QUERY: &'static str = r"INSERT INTO historyPointers (userId, lastSlot)
VALUES (?1, 1)
ON CONFLICT(userId) DO UPDATE SET
    lastSlot = (historyPointers.lastSlot % 5) + 1
RETURNING lastSlot";
    pub fn query_one(&self, client: &impl RusqliteClient) -> rusqlite::Result<RotatePointerRow> {
        Self::prepare(client)?.query_row(self.as_params(), RotatePointerRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<RotatePointerRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), RotatePointerRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (i64,) {
        (self.userid,)
    }
}
impl RotatePointer {
    pub const fn builder() -> RotatePointerBuilder<'static, ((),)> {
        RotatePointerBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct RotatePointerBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> RotatePointerBuilder<'a, ((),)> {
    pub fn userid(self, userid: i64) -> RotatePointerBuilder<'a, (i64,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        RotatePointerBuilder {
            fields: (userid,),
            _phantom,
        }
    }
}
impl<'a> RotatePointerBuilder<'a, (i64,)> {
    pub const fn build(self) -> RotatePointer {
        let (userid,) = self.fields;
        RotatePointer { userid }
    }
}
pub struct SaveHistoryRow {}
impl SaveHistoryRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {})
    }
}
pub struct SaveHistory<'a> {
    userid: i64,
    slotid: i64,
    message: &'a str,
    answer: &'a str,
    createdat: f64,
}
impl<'a> SaveHistory<'a> {
    pub const QUERY: &'static str = r"INSERT INTO userHistory (userId, slotId, message, answer, createdAt)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT(userId, slotId) DO UPDATE SET
    message = excluded.message,
    answer = excluded.answer,
    createdAt = excluded.createdAt";
    pub fn execute(&self, client: &impl RusqliteClient) -> rusqlite::Result<usize> {
        Self::prepare(client)?.execute(self.as_params())
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (i64, i64, &'a str, &'a str, f64) {
        (
            self.userid,
            self.slotid,
            self.message,
            self.answer,
            self.createdat,
        )
    }
}
impl<'a> SaveHistory<'a> {
    pub const fn builder() -> SaveHistoryBuilder<'a, ((), (), (), (), ())> {
        SaveHistoryBuilder {
            fields: ((), (), (), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct SaveHistoryBuilder<'a, Fields = ((), (), (), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Slotid, Message, Answer, Createdat>
    SaveHistoryBuilder<'a, ((), Slotid, Message, Answer, Createdat)>
{
    pub fn userid(
        self,
        userid: i64,
    ) -> SaveHistoryBuilder<'a, (i64, Slotid, Message, Answer, Createdat)> {
        let ((), slotid, message, answer, createdat) = self.fields;
        let _phantom = self._phantom;
        SaveHistoryBuilder {
            fields: (userid, slotid, message, answer, createdat),
            _phantom,
        }
    }
}
impl<'a, Userid, Message, Answer, Createdat>
    SaveHistoryBuilder<'a, (Userid, (), Message, Answer, Createdat)>
{
    pub fn slotid(
        self,
        slotid: i64,
    ) -> SaveHistoryBuilder<'a, (Userid, i64, Message, Answer, Createdat)> {
        let (userid, (), message, answer, createdat) = self.fields;
        let _phantom = self._phantom;
        SaveHistoryBuilder {
            fields: (userid, slotid, message, answer, createdat),
            _phantom,
        }
    }
}
impl<'a, Userid, Slotid, Answer, Createdat>
    SaveHistoryBuilder<'a, (Userid, Slotid, (), Answer, Createdat)>
{
    pub fn message(
        self,
        message: &'a str,
    ) -> SaveHistoryBuilder<'a, (Userid, Slotid, &'a str, Answer, Createdat)> {
        let (userid, slotid, (), answer, createdat) = self.fields;
        let _phantom = self._phantom;
        SaveHistoryBuilder {
            fields: (userid, slotid, message, answer, createdat),
            _phantom,
        }
    }
}
impl<'a, Userid, Slotid, Message, Createdat>
    SaveHistoryBuilder<'a, (Userid, Slotid, Message, (), Createdat)>
{
    pub fn answer(
        self,
        answer: &'a str,
    ) -> SaveHistoryBuilder<'a, (Userid, Slotid, Message, &'a str, Createdat)> {
        let (userid, slotid, message, (), createdat) = self.fields;
        let _phantom = self._phantom;
        SaveHistoryBuilder {
            fields: (userid, slotid, message, answer, createdat),
            _phantom,
        }
    }
}
impl<'a, Userid, Slotid, Message, Answer>
    SaveHistoryBuilder<'a, (Userid, Slotid, Message, Answer, ())>
{
    pub fn createdat(
        self,
        createdat: f64,
    ) -> SaveHistoryBuilder<'a, (Userid, Slotid, Message, Answer, f64)> {
        let (userid, slotid, message, answer, ()) = self.fields;
        let _phantom = self._phantom;
        SaveHistoryBuilder {
            fields: (userid, slotid, message, answer, createdat),
            _phantom,
        }
    }
}
impl<'a> SaveHistoryBuilder<'a, (i64, i64, &'a str, &'a str, f64)> {
    pub const fn build(self) -> SaveHistory<'a> {
        let (userid, slotid, message, answer, createdat) = self.fields;
        SaveHistory {
            userid,
            slotid,
            message,
            answer,
            createdat,
        }
    }
}
pub struct GetHistoryRow {
    pub message: String,
    pub answer: String,
}
impl GetHistoryRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            message: row.get(0)?,
            answer: row.get(1)?,
        })
    }
}
pub struct GetHistory {
    userid: i64,
}
impl GetHistory {
    pub const QUERY: &'static str = r"SELECT message, answer FROM userHistory WHERE userId = ?1 AND answer != '' ORDER BY createdAt ASC";
    pub fn query_many(&self, client: &impl RusqliteClient) -> rusqlite::Result<Vec<GetHistoryRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), GetHistoryRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (i64,) {
        (self.userid,)
    }
}
impl GetHistory {
    pub const fn builder() -> GetHistoryBuilder<'static, ((),)> {
        GetHistoryBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetHistoryBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> GetHistoryBuilder<'a, ((),)> {
    pub fn userid(self, userid: i64) -> GetHistoryBuilder<'a, (i64,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        GetHistoryBuilder {
            fields: (userid,),
            _phantom,
        }
    }
}
impl<'a> GetHistoryBuilder<'a, (i64,)> {
    pub const fn build(self) -> GetHistory {
        let (userid,) = self.fields;
        GetHistory { userid }
    }
}
pub struct GetUnannouncedTreasuryUpdatesRow {
    pub id: i64,
    pub description: String,
    pub amount: f64,
    pub createdat: f64,
}
impl GetUnannouncedTreasuryUpdatesRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            description: row.get(1)?,
            amount: row.get(2)?,
            createdat: row.get(3)?,
        })
    }
}
pub struct GetUnannouncedTreasuryUpdates;
impl GetUnannouncedTreasuryUpdates {
    pub const QUERY: &'static str = r"
SELECT id, description, amount, createdAt FROM treasuryUpdates WHERE announced = 0 ORDER BY createdAt ASC";
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<GetUnannouncedTreasuryUpdatesRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), GetUnannouncedTreasuryUpdatesRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl GetUnannouncedTreasuryUpdates {
    pub const fn builder() -> GetUnannouncedTreasuryUpdatesBuilder<'static, ()> {
        GetUnannouncedTreasuryUpdatesBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetUnannouncedTreasuryUpdatesBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> GetUnannouncedTreasuryUpdatesBuilder<'a, ()> {
    pub const fn build(self) -> GetUnannouncedTreasuryUpdates {
        let () = self.fields;
        GetUnannouncedTreasuryUpdates {}
    }
}
pub struct GetTreasuryUpdatesInPeriodRow {
    pub id: i64,
    pub description: String,
    pub amount: f64,
    pub createdat: f64,
    pub announced: i64,
}
impl GetTreasuryUpdatesInPeriodRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            id: row.get(0)?,
            description: row.get(1)?,
            amount: row.get(2)?,
            createdat: row.get(3)?,
            announced: row.get(4)?,
        })
    }
}
pub struct GetTreasuryUpdatesInPeriod {
    treasuryupdates_createdat_1: f64,
    treasuryupdates_createdat_2: f64,
}
impl GetTreasuryUpdatesInPeriod {
    pub const QUERY: &'static str = r"SELECT id, description, amount, createdAt, announced FROM treasuryUpdates WHERE createdAt >= ?1 AND createdAt <= ?2 ORDER BY createdAt ASC";
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<GetTreasuryUpdatesInPeriodRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), GetTreasuryUpdatesInPeriodRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (f64, f64) {
        (
            self.treasuryupdates_createdat_1,
            self.treasuryupdates_createdat_2,
        )
    }
}
impl GetTreasuryUpdatesInPeriod {
    pub const fn builder() -> GetTreasuryUpdatesInPeriodBuilder<'static, ((), ())> {
        GetTreasuryUpdatesInPeriodBuilder {
            fields: ((), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetTreasuryUpdatesInPeriodBuilder<'a, Fields = ((), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, TreasuryupdatesCreatedat2>
    GetTreasuryUpdatesInPeriodBuilder<'a, ((), TreasuryupdatesCreatedat2)>
{
    pub fn treasuryupdates_createdat_1(
        self,
        treasuryupdates_createdat_1: f64,
    ) -> GetTreasuryUpdatesInPeriodBuilder<'a, (f64, TreasuryupdatesCreatedat2)> {
        let ((), treasuryupdates_createdat_2) = self.fields;
        let _phantom = self._phantom;
        GetTreasuryUpdatesInPeriodBuilder {
            fields: (treasuryupdates_createdat_1, treasuryupdates_createdat_2),
            _phantom,
        }
    }
}
impl<'a, TreasuryupdatesCreatedat1>
    GetTreasuryUpdatesInPeriodBuilder<'a, (TreasuryupdatesCreatedat1, ())>
{
    pub fn treasuryupdates_createdat_2(
        self,
        treasuryupdates_createdat_2: f64,
    ) -> GetTreasuryUpdatesInPeriodBuilder<'a, (TreasuryupdatesCreatedat1, f64)> {
        let (treasuryupdates_createdat_1, ()) = self.fields;
        let _phantom = self._phantom;
        GetTreasuryUpdatesInPeriodBuilder {
            fields: (treasuryupdates_createdat_1, treasuryupdates_createdat_2),
            _phantom,
        }
    }
}
impl<'a> GetTreasuryUpdatesInPeriodBuilder<'a, (f64, f64)> {
    pub const fn build(self) -> GetTreasuryUpdatesInPeriod {
        let (treasuryupdates_createdat_1, treasuryupdates_createdat_2) = self.fields;
        GetTreasuryUpdatesInPeriod {
            treasuryupdates_createdat_1,
            treasuryupdates_createdat_2,
        }
    }
}
pub struct AddTreasuryUpdateRow {
    pub id: i64,
}
impl AddTreasuryUpdateRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self { id: row.get(0)? })
    }
}
pub struct AddTreasuryUpdate<'a> {
    description: &'a str,
    amount: f64,
    createdat: f64,
}
impl<'a> AddTreasuryUpdate<'a> {
    pub const QUERY: &'static str = r"INSERT INTO treasuryUpdates (description, amount, createdAt, announced) VALUES (?1, ?2, ?3, 0) RETURNING id";
    pub fn query_one(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<AddTreasuryUpdateRow> {
        Self::prepare(client)?.query_row(self.as_params(), AddTreasuryUpdateRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<AddTreasuryUpdateRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), AddTreasuryUpdateRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (&'a str, f64, f64) {
        (self.description, self.amount, self.createdat)
    }
}
impl<'a> AddTreasuryUpdate<'a> {
    pub const fn builder() -> AddTreasuryUpdateBuilder<'a, ((), (), ())> {
        AddTreasuryUpdateBuilder {
            fields: ((), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct AddTreasuryUpdateBuilder<'a, Fields = ((), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Amount, Createdat> AddTreasuryUpdateBuilder<'a, ((), Amount, Createdat)> {
    pub fn description(
        self,
        description: &'a str,
    ) -> AddTreasuryUpdateBuilder<'a, (&'a str, Amount, Createdat)> {
        let ((), amount, createdat) = self.fields;
        let _phantom = self._phantom;
        AddTreasuryUpdateBuilder {
            fields: (description, amount, createdat),
            _phantom,
        }
    }
}
impl<'a, Description, Createdat> AddTreasuryUpdateBuilder<'a, (Description, (), Createdat)> {
    pub fn amount(
        self,
        amount: f64,
    ) -> AddTreasuryUpdateBuilder<'a, (Description, f64, Createdat)> {
        let (description, (), createdat) = self.fields;
        let _phantom = self._phantom;
        AddTreasuryUpdateBuilder {
            fields: (description, amount, createdat),
            _phantom,
        }
    }
}
impl<'a, Description, Amount> AddTreasuryUpdateBuilder<'a, (Description, Amount, ())> {
    pub fn createdat(
        self,
        createdat: f64,
    ) -> AddTreasuryUpdateBuilder<'a, (Description, Amount, f64)> {
        let (description, amount, ()) = self.fields;
        let _phantom = self._phantom;
        AddTreasuryUpdateBuilder {
            fields: (description, amount, createdat),
            _phantom,
        }
    }
}
impl<'a> AddTreasuryUpdateBuilder<'a, (&'a str, f64, f64)> {
    pub const fn build(self) -> AddTreasuryUpdate<'a> {
        let (description, amount, createdat) = self.fields;
        AddTreasuryUpdate {
            description,
            amount,
            createdat,
        }
    }
}
pub struct SetTreasuryUpdateAnnouncedRow {}
impl SetTreasuryUpdateAnnouncedRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {})
    }
}
pub struct SetTreasuryUpdateAnnounced {
    id: i64,
}
impl SetTreasuryUpdateAnnounced {
    pub const QUERY: &'static str = r"UPDATE treasuryUpdates SET announced = 1 WHERE id = ?1";
    pub fn execute(&self, client: &impl RusqliteClient) -> rusqlite::Result<usize> {
        Self::prepare(client)?.execute(self.as_params())
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (i64,) {
        (self.id,)
    }
}
impl SetTreasuryUpdateAnnounced {
    pub const fn builder() -> SetTreasuryUpdateAnnouncedBuilder<'static, ((),)> {
        SetTreasuryUpdateAnnouncedBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct SetTreasuryUpdateAnnouncedBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> SetTreasuryUpdateAnnouncedBuilder<'a, ((),)> {
    pub fn id(self, id: i64) -> SetTreasuryUpdateAnnouncedBuilder<'a, (i64,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        SetTreasuryUpdateAnnouncedBuilder {
            fields: (id,),
            _phantom,
        }
    }
}
impl<'a> SetTreasuryUpdateAnnouncedBuilder<'a, (i64,)> {
    pub const fn build(self) -> SetTreasuryUpdateAnnounced {
        let (id,) = self.fields;
        SetTreasuryUpdateAnnounced { id }
    }
}
pub struct GetAllAssociateEmailsRow {
    pub email: String,
}
impl GetAllAssociateEmailsRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self { email: row.get(0)? })
    }
}
pub struct GetAllAssociateEmails;
impl GetAllAssociateEmails {
    pub const QUERY: &'static str = r"SELECT email FROM associates";
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<GetAllAssociateEmailsRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), GetAllAssociateEmailsRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl GetAllAssociateEmails {
    pub const fn builder() -> GetAllAssociateEmailsBuilder<'static, ()> {
        GetAllAssociateEmailsBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetAllAssociateEmailsBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> GetAllAssociateEmailsBuilder<'a, ()> {
    pub const fn build(self) -> GetAllAssociateEmails {
        let () = self.fields;
        GetAllAssociateEmails {}
    }
}
pub struct AddAssociateRow {
    pub nickname: String,
}
impl AddAssociateRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            nickname: row.get(0)?,
        })
    }
}
pub struct AddAssociate<'a> {
    nickname: &'a str,
    email: &'a str,
}
impl<'a> AddAssociate<'a> {
    pub const QUERY: &'static str = r"INSERT INTO associates (nickName, email) VALUES (?1, ?2) ON CONFLICT(nickName) DO NOTHING RETURNING nickName";
    pub fn query_one(&self, client: &impl RusqliteClient) -> rusqlite::Result<AddAssociateRow> {
        Self::prepare(client)?.query_row(self.as_params(), AddAssociateRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<AddAssociateRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), AddAssociateRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (&'a str, &'a str) {
        (self.nickname, self.email)
    }
}
impl<'a> AddAssociate<'a> {
    pub const fn builder() -> AddAssociateBuilder<'a, ((), ())> {
        AddAssociateBuilder {
            fields: ((), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct AddAssociateBuilder<'a, Fields = ((), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Email> AddAssociateBuilder<'a, ((), Email)> {
    pub fn nickname(self, nickname: &'a str) -> AddAssociateBuilder<'a, (&'a str, Email)> {
        let ((), email) = self.fields;
        let _phantom = self._phantom;
        AddAssociateBuilder {
            fields: (nickname, email),
            _phantom,
        }
    }
}
impl<'a, Nickname> AddAssociateBuilder<'a, (Nickname, ())> {
    pub fn email(self, email: &'a str) -> AddAssociateBuilder<'a, (Nickname, &'a str)> {
        let (nickname, ()) = self.fields;
        let _phantom = self._phantom;
        AddAssociateBuilder {
            fields: (nickname, email),
            _phantom,
        }
    }
}
impl<'a> AddAssociateBuilder<'a, (&'a str, &'a str)> {
    pub const fn build(self) -> AddAssociate<'a> {
        let (nickname, email) = self.fields;
        AddAssociate { nickname, email }
    }
}
pub struct RemoveAssociateRow {}
impl RemoveAssociateRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {})
    }
}
pub struct RemoveAssociate<'a> {
    nickname: &'a str,
}
impl<'a> RemoveAssociate<'a> {
    pub const QUERY: &'static str = r"DELETE FROM associates WHERE nickName = ?1";
    pub fn execute(&self, client: &impl RusqliteClient) -> rusqlite::Result<usize> {
        Self::prepare(client)?.execute(self.as_params())
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (&'a str,) {
        (self.nickname,)
    }
}
impl<'a> RemoveAssociate<'a> {
    pub const fn builder() -> RemoveAssociateBuilder<'a, ((),)> {
        RemoveAssociateBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct RemoveAssociateBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> RemoveAssociateBuilder<'a, ((),)> {
    pub fn nickname(self, nickname: &'a str) -> RemoveAssociateBuilder<'a, (&'a str,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        RemoveAssociateBuilder {
            fields: (nickname,),
            _phantom,
        }
    }
}
impl<'a> RemoveAssociateBuilder<'a, (&'a str,)> {
    pub const fn build(self) -> RemoveAssociate<'a> {
        let (nickname,) = self.fields;
        RemoveAssociate { nickname }
    }
}
pub struct ListAssociatesRow {
    pub nickname: String,
    pub email: String,
}
impl ListAssociatesRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            nickname: row.get(0)?,
            email: row.get(1)?,
        })
    }
}
pub struct ListAssociates;
impl ListAssociates {
    pub const QUERY: &'static str = r"SELECT nickName, email FROM associates";
    pub fn query_many(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Vec<ListAssociatesRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), ListAssociatesRow::from_row)?
            .collect()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> () {
        ()
    }
}
impl ListAssociates {
    pub const fn builder() -> ListAssociatesBuilder<'static, ()> {
        ListAssociatesBuilder {
            fields: (),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct ListAssociatesBuilder<'a, Fields = ()> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> ListAssociatesBuilder<'a, ()> {
    pub const fn build(self) -> ListAssociates {
        let () = self.fields;
        ListAssociates {}
    }
}
pub struct GetAssociateRow {
    pub nickname: String,
    pub email: String,
}
impl GetAssociateRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {
            nickname: row.get(0)?,
            email: row.get(1)?,
        })
    }
}
pub struct GetAssociate<'a> {
    nickname: &'a str,
}
impl<'a> GetAssociate<'a> {
    pub const QUERY: &'static str = r"SELECT nickName, email FROM associates WHERE nickName = ?1";
    pub fn query_one(&self, client: &impl RusqliteClient) -> rusqlite::Result<GetAssociateRow> {
        Self::prepare(client)?.query_row(self.as_params(), GetAssociateRow::from_row)
    }
    pub fn query_opt(
        &self,
        client: &impl RusqliteClient,
    ) -> rusqlite::Result<Option<GetAssociateRow>> {
        Self::prepare(client)?
            .query_map(self.as_params(), GetAssociateRow::from_row)?
            .next()
            .transpose()
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (&'a str,) {
        (self.nickname,)
    }
}
impl<'a> GetAssociate<'a> {
    pub const fn builder() -> GetAssociateBuilder<'a, ((),)> {
        GetAssociateBuilder {
            fields: ((),),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct GetAssociateBuilder<'a, Fields = ((),)> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a> GetAssociateBuilder<'a, ((),)> {
    pub fn nickname(self, nickname: &'a str) -> GetAssociateBuilder<'a, (&'a str,)> {
        let ((),) = self.fields;
        let _phantom = self._phantom;
        GetAssociateBuilder {
            fields: (nickname,),
            _phantom,
        }
    }
}
impl<'a> GetAssociateBuilder<'a, (&'a str,)> {
    pub const fn build(self) -> GetAssociate<'a> {
        let (nickname,) = self.fields;
        GetAssociate { nickname }
    }
}
pub struct UpdateAssociateRow {}
impl UpdateAssociateRow {
    pub fn from_row(row: &rusqlite::Row) -> rusqlite::Result<Self> {
        Ok(Self {})
    }
}
pub struct UpdateAssociate<'a> {
    associates_nickname_1: &'a str,
    email: &'a str,
    associates_nickname_2: &'a str,
}
impl<'a> UpdateAssociate<'a> {
    pub const QUERY: &'static str =
        r"UPDATE associates SET nickName = ?1, email = ?2 WHERE nickName = ?3";
    pub fn execute(&self, client: &impl RusqliteClient) -> rusqlite::Result<usize> {
        Self::prepare(client)?.execute(self.as_params())
    }
    pub fn prepare<'conn>(
        client: &'conn impl RusqliteClient,
    ) -> rusqlite::Result<rusqlite::Statement<'conn>> {
        client.prepare(Self::QUERY)
    }
    pub fn as_params(&self) -> (&'a str, &'a str, &'a str) {
        (
            self.associates_nickname_1,
            self.email,
            self.associates_nickname_2,
        )
    }
}
impl<'a> UpdateAssociate<'a> {
    pub const fn builder() -> UpdateAssociateBuilder<'a, ((), (), ())> {
        UpdateAssociateBuilder {
            fields: ((), (), ()),
            _phantom: std::marker::PhantomData,
        }
    }
}
pub struct UpdateAssociateBuilder<'a, Fields = ((), (), ())> {
    fields: Fields,
    _phantom: std::marker::PhantomData<&'a ()>,
}
impl<'a, Email, AssociatesNickname2> UpdateAssociateBuilder<'a, ((), Email, AssociatesNickname2)> {
    pub fn associates_nickname_1(
        self,
        associates_nickname_1: &'a str,
    ) -> UpdateAssociateBuilder<'a, (&'a str, Email, AssociatesNickname2)> {
        let ((), email, associates_nickname_2) = self.fields;
        let _phantom = self._phantom;
        UpdateAssociateBuilder {
            fields: (associates_nickname_1, email, associates_nickname_2),
            _phantom,
        }
    }
}
impl<'a, AssociatesNickname1, AssociatesNickname2>
    UpdateAssociateBuilder<'a, (AssociatesNickname1, (), AssociatesNickname2)>
{
    pub fn email(
        self,
        email: &'a str,
    ) -> UpdateAssociateBuilder<'a, (AssociatesNickname1, &'a str, AssociatesNickname2)> {
        let (associates_nickname_1, (), associates_nickname_2) = self.fields;
        let _phantom = self._phantom;
        UpdateAssociateBuilder {
            fields: (associates_nickname_1, email, associates_nickname_2),
            _phantom,
        }
    }
}
impl<'a, AssociatesNickname1, Email> UpdateAssociateBuilder<'a, (AssociatesNickname1, Email, ())> {
    pub fn associates_nickname_2(
        self,
        associates_nickname_2: &'a str,
    ) -> UpdateAssociateBuilder<'a, (AssociatesNickname1, Email, &'a str)> {
        let (associates_nickname_1, email, ()) = self.fields;
        let _phantom = self._phantom;
        UpdateAssociateBuilder {
            fields: (associates_nickname_1, email, associates_nickname_2),
            _phantom,
        }
    }
}
impl<'a> UpdateAssociateBuilder<'a, (&'a str, &'a str, &'a str)> {
    pub const fn build(self) -> UpdateAssociate<'a> {
        let (associates_nickname_1, email, associates_nickname_2) = self.fields;
        UpdateAssociate {
            associates_nickname_1,
            email,
            associates_nickname_2,
        }
    }
}
